### ISSUE TITLE
Report issue related to mixing Xtend and Java and building with Gradle

### ISSUE THREAD

**Issue by imbur** [FTSRG/BME-MODES3#40]

**Comment by benedekh** [comment]
Closed, because the bug is not _deterministically_ reproducible even with commits before https://github.com/FTSRG/BME-MODES3/commit/f520036b34637465b285aa0ed92aa018bfb5e18e, e.g. https://github.com/FTSRG/BME-MODES3/commit/0b2a9c06db8243be4d10e338393a6ab0d15f009a, even by removing project which ':components:safetylogic:hu.bme.mit.inf.modes3.components.safetylogic.componentlevel.sc' does not depend on. The mentioned project included the (possible) cause of the bug.

The possible cause of the bug was mixing Xtend codes with Java codes in the same _source_ set and trying to build the project with Gradle Xtend (builder) plugin. Version 1.0.12. (id "org.xtext.xtend" version "1.0.12")
