### ISSUE TITLE
Clean up interfaces for the state machines of the safety logic

### ISSUE THREAD

**Issue by imbur** [FTSRG/BME-MODES3#5]

**Comment by benedekh** [comment]
@imbur May you explain the purpose of this issue? Thank you.

**Comment by benedekh** [comment]
It will not be fixed before the Researchers' night event. There was a discussion about this issue that recommended to define an interface which contains the common methods for the safetylogic components. Although this interface is nice to have, it has several drawbacks:
1. The safetylogic implementations receive the section status information over the network. So the incoming methods are the messages which the respective safetylogic implementation receives. There is a common implementation for receiving section status (occupancy, enabled/disabled) and turnout status (straight/divergent) information over the network. This common implementation is called [TrackCommunicationServiceLocator](https://github.com/FTSRG/BME-MODES3/blob/gen3-arch/src/java/messaging/hu.bme.mit.inf.modes3.messaging.communication/src/main/java/hu/bme/mit/inf/modes3/messaging/communication/factory/TrackCommunicationServiceLocator.xtend) which provides a [TrackElementStateRegistry](https://github.com/FTSRG/BME-MODES3/blob/gen3-arch/src/java/messaging/hu.bme.mit.inf.modes3.messaging.communication/src/main/java/hu/bme/mit/inf/modes3/messaging/communication/state/TrackElementStateRegistry.xtend) field from which the required information can be obtained.
2. If the safetylogic implementation makes a decision so that a section should be disabled/enabled then it can send this command over the network using the aforementioned [TrackCommunicationServiceLocator](https://github.com/FTSRG/BME-MODES3/blob/gen3-arch/src/java/messaging/hu.bme.mit.inf.modes3.messaging.communication/src/main/java/hu/bme/mit/inf/modes3/messaging/communication/factory/TrackCommunicationServiceLocator.xtend)'s [TrackElementCommander](https://github.com/FTSRG/BME-MODES3/blob/gen3-arch/src/java/messaging/hu.bme.mit.inf.modes3.messaging.communication/src/main/java/hu/bme/mit/inf/modes3/messaging/communication/command/TrackElementCommander.xtend) field. So these messages are the 'outgoing' messages while the incoming messages can be guessed from the previous point.
3. May it be required in the future, I leave the draft of the common interface here as an attachment: [interface draft](https://cloud.githubusercontent.com/assets/8940487/18670140/b138f354-7f3e-11e6-9f85-298ac54b0dc5.png)
