### ISSUE TITLE
Segment occupancies are not shown on Dashboard

### ISSUE THREAD

**Issue by benedekh** [FTSRG/BME-MODES3#99]
Since the changes to the DashboardManager were committed, neither the occupancies nor the segment / turnout statuses are displayed.

A log entry for a missing handler for occupancy message:

```
[pool-1-thread-77] WARN org.atmosphere.cpr.DefaultMetaBroadcaster - No Broadcaster matches /ws/state/segmentoccupancy. Message {
  "segmentID": 6,
  "state": "FREE"
} WILL BE LOST. Make sure you cache it or make sure the Broadcaster exists before.
```

However, the segments / turnouts are clickable and the corresponding commands are sent to the table. After that the turnout/segment statuses are displayed correctly, but the segment occupancy is still missing.

**Comment by zsoltmazlo** [comment]
It is an intentional change in the UI code as you can see in  [setup.js](https://github.com/FTSRG/BME-MODES3/blob/dfc21cf8714a0f60a6542ecc7b6ee182152e9f40/src/java/components/hu.bme.mit.inf.modes3.components.dashboard/src/main/webapp/public_html/js/setup.js#L27) - from now, we are tracking the position of each train based on the information received from CV and it might be confusing to show occupancy too.
